### ISSUE TITLE
Calling a profiled function twice in one frame generates separate spans for them in puffin-imgui

### ISSUE THREAD

**Issue by JMS55** [EmbarkStudios/puffin#3]
![image](https://user-images.githubusercontent.com/47158642/90457470-9d47d400-e0c9-11ea-8af6-d891f3ca086b.png)

As you can see, move_particles has 4485 children, yet all of them are really the same function. Maybe it makes sense for each macro to take an option on whether to combine records of the same name or not, during the same frame.

For something like this, where the function runs pretty much the same length every time, it would be better to combine them.

For a function you only call 2-10 times per frame, which could vary in length greatly, it would make more sense to keep them separate.

**Comment by emilk** [comment]
Sometimes you want to see all the events, sometimes the aggregate. Combining subsequent scopes with the same id is not possible at capture time without adding a lot of overhead (since the scopes can have children of their own).

The simpler solution is a GUI option to combine children of the same id. [That's how I've done it before](https://github.com/emilk/emilib/blob/master/emilib/profiler_gui.cpp#L211).
